"""Regenerate the machine-derived reference docs so they cannot drift from the code:

    docs/generated/mcp_tools.md       every MCP tool of the three servers (name, description, parameters) — read from the live FastMCP objects
    docs/generated/operator_api.md    every operator-API endpoint (method, path, summary, parameters, body model) — read from the FastAPI app
    docs/generated/openapi.json       the OpenAPI document of the operator API

    ./.venv/bin/python scripts/gen_docs.py      (or: make docs)
"""
from __future__ import annotations

import asyncio
import importlib.util
import json
import os
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "docs" / "generated"
os.environ.setdefault("COGNEE_ENABLED", "0")
sys.path[:0] = [str(REPO), str(REPO / "agent"), str(REPO / "ml"), str(REPO / "dashboard"), str(REPO / "backend"), str(REPO / "mcp_server")]


def load(path: str, name: str):
    spec = importlib.util.spec_from_file_location(name, REPO / path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


def first_para(text: str | None) -> str:
    text = (text or "").strip()
    return " ".join(text.split("\n\n")[0].split())


async def tools_of(mcp):
    if hasattr(mcp, "list_tools"):
        got = await mcp.list_tools()
    else:
        got = list((await mcp.get_tools()).values())
    return sorted(got, key=lambda t: t.name)


def params(schema: dict | None) -> str:
    props = (schema or {}).get("properties", {})
    req = set((schema or {}).get("required", []))
    out = []
    for k, v in props.items():
        t = v.get("type") or "/".join(x.get("type", "?") for x in v.get("anyOf", []) if isinstance(x, dict)) or "any"
        out.append(f"`{k}`{'' if k in req else '?'}: {t}")
    return ", ".join(out) or "—"


def mcp_doc() -> str:
    servers = [
        ("data server — `mcp_server/server.py` (stdio, spawned by the agent; optional HTTP with `--with-data-mcp`)", "mcp_server/server.py", "nextmove_data_server"),
        ("knowledge server — `mcp_server/knowledge_server.py` (HTTP :8766)", "mcp_server/knowledge_server.py", "nextmove_knowledge_server"),
        ("quality server — `mcp_server/quality_server.py` (HTTP :8768; also in-process via `agent/quality_mcp.py`)", "mcp_server/quality_server.py", "nextmove_quality_server"),
    ]
    lines = ["# MCP tool catalogue (generated)", "", "Generated by `scripts/gen_docs.py` from the live FastMCP objects — do not edit by hand. Narrative: [../mcp_and_tools.md](../mcp_and_tools.md).", ""]
    for title, path, name in servers:
        try:
            mod = load(path, name)
            tools = asyncio.run(tools_of(mod.mcp))
        except Exception as e:  # keep going: a server that cannot be imported here must not block the other docs
            lines += [f"## {title}", "", f"_could not be loaded: {type(e).__name__}: {e}_", ""]
            continue
        lines += [f"## {title}", "", f"{len(tools)} tools.", "", "| tool | what it does | parameters |", "|---|---|---|"]
        for t in tools:
            lines.append(f"| `{t.name}` | {first_para(t.description).replace('|', '/')} | {params(getattr(t, 'parameters', None) or getattr(t, 'inputSchema', None))} |")
        lines.append("")
    return "\n".join(lines)


def api_doc() -> tuple[str, dict]:
    op = load("backend/operator_api.py", "operator_api_docgen")
    spec = op.app.openapi()
    lines = ["# Operator API endpoints (generated)", "", "Generated by `scripts/gen_docs.py` from the FastAPI app — do not edit by hand. Narrative, examples and the SSE format: [../api_reference.md](../api_reference.md). Live docs: http://127.0.0.1:8770/docs .", "",
             "| method | path | summary | parameters / body |", "|---|---|---|---|"]
    for path, ops in sorted(spec["paths"].items()):
        for method, o in ops.items():
            ps = ", ".join(f"`{p['name']}`{'' if p.get('required') else '?'} ({p['in']})" for p in o.get("parameters", []))
            body = o.get("requestBody", {}).get("content", {}).get("application/json", {}).get("schema", {}).get("$ref", "")
            if body:
                name = body.rsplit("/", 1)[-1]
                fields = ", ".join(f"`{k}`" for k in spec["components"]["schemas"].get(name, {}).get("properties", {}))
                ps = (ps + "; " if ps else "") + f"body **{name}**: {fields}"
            summ = first_para(o.get("description") or o.get("summary") or "").replace("|", "/")
            lines.append(f"| {method.upper()} | `{path}` | {summ} | {ps or '—'} |")
    return "\n".join(lines) + "\n", spec


if __name__ == "__main__":
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "mcp_tools.md").write_text(mcp_doc())
    md, spec = api_doc()
    (OUT / "operator_api.md").write_text(md)
    (OUT / "openapi.json").write_text(json.dumps(spec, indent=1))
    print("written:", *(str(p.relative_to(REPO)) for p in sorted(OUT.iterdir())))
