"""ONE schema for everything that moves between the agents, the MCP servers and the stores.

    question ─► SUPERVISOR ─► SupervisorPlan ─► WORKER ─► WorkerResult ─► EVALUATOR ─► EvaluatorVerdict ─┐
                  │  (guardrails, history,          ▲  (feedback loop: verdict.adjustments → new WorkerTask)  │
                  │   follow-up, route)             └───────────────────────────────────────────────────────┘
                  └─ bounce / decline / answer-from-history ──────────────────────► FinalAnswer ◄── WRITER ◄── WriterInput

Every message is a pydantic model with `extra="forbid"` (an unknown key is an error, not silently carried along) and a
`schema_version`. They are validated at each hand-over — a malformed message is a hard failure that ends in the safe answer, never in a
guess. JSON Schemas are generated by `export_json_schemas()` (make schemas → docs/schemas/*.json) and described in docs/agent_schemas.md.

The playbooks (agent/specialists.py) and the writer still speak the compact `facts` / `plan` dicts they always did: `SupervisorPlan.to_legacy()`
and `WorkerTask.to_legacy_plan()` are the single adapters, so there is exactly one place where the two vocabularies meet.
"""
from __future__ import annotations

import time
import uuid
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

SCHEMA_VERSION = "1.0"

Category = Literal["A", "B", "C", "D", "E", "F", "G", "H", "P", "X", "OOS", "FOLLOW", "BOUNCE"]
Decision = Literal["proceed", "answer_from_history", "follow_up", "decline", "need_input", "bounce"]
MlEngine = Literal["tabpfn", "empirical", "none"]
ObjectiveKind = Literal["explain_closure", "closure_impact", "station_profile", "event_effect", "load_ranking", "anomaly_cause", "energy_efficiency",
                        "resilience_ranking", "demand_coupling", "reroute_evidence", "follow_up", "decline", "bounce"]


class _M(BaseModel):
    model_config = ConfigDict(extra="forbid")


def _id(prefix: str) -> str:
    return f"{prefix}-{uuid.uuid4().hex[:10]}"


# =============================================================================================== guardrails
class GuardrailResult(_M):
    """One guardrail check. `action` is what the system did about a failure: allow | bounce (unrelated question, conversation cut) |
    cut (stop the loop) | repair (fix the output deterministically) | fallback (safe deterministic answer) | escalate (flag low confidence)."""
    stage: Literal["input", "route", "worker", "evaluator", "output", "failsafe"]
    check: str
    passed: bool
    action: Literal["allow", "bounce", "cut", "repair", "fallback", "escalate"] = "allow"
    detail: str = ""


# =============================================================================================== supervisor
class Entities(_M):
    """Parameters the supervisor extracts from the question (station names are the data's exact strings)."""
    lines: list[str] = []
    stations: list[str] = []
    dates: list[str] = []                 # ISO dates
    times: list[str] = []                 # 'HH:MM', in the order they appear
    duration_min: int | None = None
    horizon_min: int | None = None        # look-ahead ('in the next 20 minutes'), NOT a duration
    venue: str | None = None
    venue_alias_used: bool = False
    event: str | None = None
    top_n: int | None = None
    rain: bool | None = None
    relative_day: str | None = None       # 'tonight' / 'tomorrow' — no calendar date in the data
    what_if: bool = False
    month: str | None = None
    unresolved_places: list[str] = []
    out_of_scope_terms: list[str] = []    # e.g. 'capacity': asked for, but the data has none
    assumptions: list[str] = []           # made by the supervisor on the operator's behalf (e.g. InnoTrans day 1)

    @classmethod
    def from_legacy(cls, p: dict) -> "Entities":
        return cls(lines=p.get("lines") or [], stations=p.get("stations") or [], dates=p.get("dates") or [], times=p.get("times") or ([p["time"]] if p.get("time") else []),
                   duration_min=p.get("dur_min"), horizon_min=p.get("horizon_min"), venue=p.get("venue"), venue_alias_used=bool(p.get("alias")), event=p.get("event"),
                   top_n=p.get("n"), rain=p.get("rain"), relative_day=p.get("rel_day"), what_if=bool(p.get("what_if")), month=p.get("month"),
                   unresolved_places=p.get("raw") or [], out_of_scope_terms=p.get("oos") or [], assumptions=list(p.get("assumed") or []))

    def to_legacy(self) -> dict:
        return {"lines": self.lines, "stations": self.stations, "dates": self.dates, "times": self.times, "time": self.times[0] if self.times else None,
                "dur_min": self.duration_min, "horizon_min": self.horizon_min, "venue": self.venue, "alias": self.venue_alias_used, "event": self.event,
                "n": self.top_n, "rain": self.rain, "rel_day": self.relative_day, "what_if": self.what_if, "month": self.month, "raw": self.unresolved_places,
                "oos": self.out_of_scope_terms, "assumed": self.assumptions}


class Objective(_M):
    """What a good answer must achieve — the yardstick the evaluator checks the worker's result against."""
    kind: ObjectiveKind
    statement: str
    success_criteria: list[str] = []


class Route(_M):
    """Which specialist, MCP servers, datasets, tools and ML engine the supervisor assigns to the question."""
    specialist: str
    mcp_servers: list[str] = []
    datasets: list[str] = []
    tools: list[str] = []
    ml_engine: MlEngine = "none"


class HistoryHit(_M):
    """A previous, ACCEPTED answer (local turn store, mirrored to Cognee sessions) that already answers this question."""
    kind: Literal["exact", "similar"]
    turn_id: int
    session_id: str
    similarity: float
    question: str
    answer: str
    category: str
    confidence: float | None = None
    age_s: float
    data_window_end: str | None = None


class FollowUp(_M):
    """The question continues an earlier one. `mode`: explain = answer from the earlier facts; rerun = same specialist with inherited
    parameters and the operator's changes applied ('start from that point')."""
    mode: Literal["explain", "rerun"]
    parent_category: str
    inherited: list[str] = []
    overridden: dict[str, Any] = {}


class PartPlan(_M):
    """One question inside a multi-question message."""
    text: str
    category: Category
    confidence: float
    entities: Entities
    route: Route


class SupervisorPlan(_M):
    schema_version: str = SCHEMA_VERSION
    plan_id: str = Field(default_factory=lambda: _id("plan"))
    question: str
    decision: Decision
    in_scope: bool
    category: Category
    confidence: float
    tier: int = 0                          # 0 rules · 1 small-LLM fallback · 2 tf-idf
    entities: Entities = Entities()
    objective: Objective
    route: Route
    guardrails: list[GuardrailResult] = []
    history: HistoryHit | None = None
    follow_up: FollowUp | None = None
    parts: list[PartPlan] = []
    message: str | None = None             # the deterministic reply for bounce / decline-before-work
    kb_boundaries: list[str] = []
    llm_router_error: str | None = None

    def to_legacy(self) -> dict:
        """The plan dict the playbooks / executor / metrics understand."""
        from router import CAT_DATA

        p = {"cat": self.category, "conf": self.confidence, "tier": self.tier, **CAT_DATA.get(self.category, {}), **self.entities.to_legacy(), "follow": self.category == "FOLLOW",
             "kb": self.kb_boundaries}
        p["tools"] = self.route.tools or p.get("tools", [])
        if self.parts:
            p["parts"] = [{"text": x.text, "cat": x.category, "conf": x.confidence, "tier": 0, **CAT_DATA.get(x.category, {}), **x.entities.to_legacy(), "follow": False} for x in self.parts]
        return p


# =============================================================================================== worker
class WorkerTask(_M):
    """What the supervisor hands to the worker: the tools, datasets and ML engine to use and the objective to reach. Iteration > 1 carries the
    evaluator's `overrides`."""
    schema_version: str = SCHEMA_VERSION
    task_id: str = Field(default_factory=lambda: _id("task"))
    plan_id: str
    iteration: int = 1
    question: str
    category: Category
    objective: Objective
    entities: Entities
    route: Route
    parts: list[PartPlan] = []
    overrides: dict[str, Any] = {}

    def to_legacy_plan(self) -> dict:
        p = {"cat": self.category, "conf": 1.0, "tier": 0, **self.entities.to_legacy(), "follow": False, "tools": self.route.tools}
        from router import CAT_DATA
        p.update({k: v for k, v in CAT_DATA.get(self.category, {}).items() if k != "tools"})
        if self.parts:
            p["parts"] = [{"text": x.text, "cat": x.category, "conf": x.confidence, "tier": 0, **x.entities.to_legacy(), "follow": False,
                           **{k: v for k, v in CAT_DATA.get(x.category, {}).items()}} for x in self.parts]
        return p


class ToolCall(_M):
    tool: str
    server: str = "ubahn-flow-data"
    seconds: float = 0.0


class WorkerResult(_M):
    """The worker's output: the compact facts, how confident it is and why, and what it touched."""
    schema_version: str = SCHEMA_VERSION
    task_id: str
    iteration: int
    status: Literal["ok", "need", "unsupported", "oos", "follow", "multi", "error"]
    facts: dict[str, Any]
    confidence: float = Field(ge=0.0, le=1.0)
    confidence_reasons: list[str] = []
    assumptions: list[str] = []
    datasets_used: list[str] = []
    tools_called: list[ToolCall] = []
    ml_engine_used: MlEngine = "none"
    seconds: float = 0.0


# =============================================================================================== evaluator
class Adjustments(_M):
    """What the evaluator may ask the worker to change on the next iteration (a closed list: nothing else can be overridden)."""
    dates: list[str] | None = None
    times: list[str] | None = None
    stations: list[str] | None = None
    top_n: int | None = None
    rain: bool | None = None
    duration_min: int | None = None
    ml_engine: MlEngine | None = None

    def is_empty(self) -> bool:
        return not any(v is not None for v in self.model_dump().values())


class CheckResult(_M):
    id: str
    ok: bool
    detail: str = ""


class KGCase(_M):
    """A past problem with its accepted answer, the actions taken and the options offered (from the knowledge graph)."""
    problem_id: str
    problem: str
    category: str
    similarity: float
    answer: str = ""
    actions: list[str] = []
    options: list[str] = []
    times_accepted: int = 0


class EvaluatorVerdict(_M):
    schema_version: str = SCHEMA_VERSION
    task_id: str
    iteration: int
    verdict: Literal["accept", "revise", "reject"]
    objective_met: bool
    score: float = Field(ge=0.0, le=1.0)
    issues: list[str] = []
    adjustments: Adjustments | None = None
    checks: list[CheckResult] = []
    ground_truth_ids: list[str] = []
    boundary_ids: list[str] = []
    similar_cases: list[KGCase] = []
    rationale: str = ""
    model: str = "deterministic"           # 'deterministic' or the LLM that judged
    seconds: float = 0.0


# =============================================================================================== writer
class Reference(_M):
    kind: Literal["dataset", "tool", "kb", "kg", "model"]
    id: str
    note: str = ""


class WriterInput(_M):
    """Insights and results for the writer: verdict first, then evidence and references; an argument only if the operator asks why."""
    schema_version: str = SCHEMA_VERSION
    question: str
    objective: Objective
    verdict: EvaluatorVerdict
    result: WorkerResult
    references: list[Reference] = []
    wants_argument: bool = False


class FinalAnswer(_M):
    schema_version: str = SCHEMA_VERSION
    plan_id: str
    text: str
    decision: Decision
    category: Category
    confidence: float | None = None
    verdict: str | None = None
    references: list[Reference] = []
    guardrails: list[GuardrailResult] = []
    iterations: int = 0
    seconds: float = 0.0
    source: Literal["worker", "history", "bounce", "decline", "safe_fallback", "follow_up"] = "worker"


# =============================================================================================== knowledge graph
NODE_LABELS = ("Category", "Problem", "Answer", "Action", "Option", "Station", "Line", "Venue", "Event", "Document", "Concept")
REL_TYPES = ("IN_CATEGORY", "ANSWERED_BY", "RECOMMENDS", "OFFERS_OPTION", "INVOLVES", "AT", "SIMILAR_TO", "SUPPORTED_BY", "FROM_DOCUMENT", "RELATED_TO")


class GraphNode(_M):
    label: str
    key: str
    props: dict[str, Any] = {}


class GraphEdge(_M):
    src: tuple[str, str]                   # (label, key)
    rel: str
    dst: tuple[str, str]
    props: dict[str, Any] = {}


class GraphCase(_M):
    """A problem → answer → actions/options record, the unit the graph grows by."""
    question: str
    category: str
    entities: Entities
    answer: str
    confidence: float | None = None
    verdict: str | None = None
    actions: list[str] = []
    options: list[str] = []
    source: str = "runtime"                # runtime | seed:closure | seed:training | seed:bank | llm-graph-builder
    ts: float = Field(default_factory=time.time)


# =============================================================================================== export
def export_json_schemas(out_dir) -> list[str]:
    """Write one JSON Schema per top-level message (docs/schemas/*.json) — what an external agent / MCP client validates against."""
    import json
    from pathlib import Path

    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    models = {"SupervisorPlan": SupervisorPlan, "WorkerTask": WorkerTask, "WorkerResult": WorkerResult, "EvaluatorVerdict": EvaluatorVerdict,
              "WriterInput": WriterInput, "FinalAnswer": FinalAnswer, "GraphCase": GraphCase, "GuardrailResult": GuardrailResult}
    names = []
    for n, m in models.items():
        (out / f"{n}.schema.json").write_text(json.dumps(m.model_json_schema(), indent=1))
        names.append(n)
    return names


if __name__ == "__main__":
    from pathlib import Path

    out = Path(__file__).resolve().parent.parent / "docs" / "schemas"
    print("wrote", ", ".join(export_json_schemas(out)), "->", out)
